// Pure Notion -> markdown helpers. No API calls and no env reads, so they can be
// exercised on their own: `node scripts/md.mjs`.
import assert from "node:assert/strict";

export const plain = (rich) => (rich ?? []).map((t) => t.plain_text).join("");

export function rich(arr) {
  return (arr ?? [])
    .map((t) => {
      let s = t.plain_text.replace(/([*_`[\]])/g, "\\$1");
      const a = t.annotations ?? {};
      if (a.code) s = `\`${t.plain_text}\``;
      if (a.bold) s = `**${s}**`;
      if (a.italic) s = `*${s}*`;
      if (t.href) s = `[${s}](${t.href})`;
      return s;
    })
    .join("");
}

export const SLUG_RE = /^[a-z0-9-]+$/;

// Keys are emitted in sorted order and last_edited_time is deliberately absent:
// either would make the output differ between runs and turn every PR into noise.
export function frontmatter(obj, notionUrl) {
  const q = (v) => (typeof v === "string" ? JSON.stringify(v) : String(v));
  const lines = ["---", `# GENERATED FROM NOTION — do not edit this file. Source: ${notionUrl}`];
  for (const key of Object.keys(obj).sort()) {
    const v = obj[key];
    if (v === undefined || v === null || v === "" || (Array.isArray(v) && !v.length)) continue;
    if (Array.isArray(v)) lines.push(`${key}:`, ...v.map((x) => `  - ${q(x)}`));
    else lines.push(`${key}: ${q(v)}`);
  }
  lines.push("---", "");
  return lines.join("\n");
}

// --- self-check ------------------------------------------------------------
function demo() {
  const t = (text, annotations = {}, href = null) => ({ plain_text: text, annotations, href });

  assert.equal(rich([t("hello")]), "hello");
  assert.equal(rich([t("hi", { bold: true })]), "**hi**");
  assert.equal(rich([t("hi", { italic: true, bold: true })]), "***hi***");
  assert.equal(rich([t("NAU", {}, "https://nerdyau.com")]), "[NAU](https://nerdyau.com)");
  // Markdown metacharacters in Notion text must not become markup.
  assert.equal(rich([t("2 * 3 _ 4")]), "2 \\* 3 \\_ 4");
  // Code spans keep their literal text rather than the escaped copy.
  assert.equal(rich([t("a_b", { code: true })]), "`a_b`");

  assert.ok(SLUG_RE.test("kia-ev9-2024"));
  assert.ok(!SLUG_RE.test("기아-ev9"));
  assert.ok(!SLUG_RE.test("Kia EV9"));

  // Idempotency: property order in the input must not change the output bytes.
  const a = frontmatter({ title: "T", date: "2025-01-01", credits: ["김", "이"] }, "u");
  const b = frontmatter({ credits: ["김", "이"], title: "T", date: "2025-01-01" }, "u");
  assert.equal(a, b);
  assert.match(a, /^---\n# GENERATED FROM NOTION/);
  // Empty values are dropped so an unset Notion property does not emit a key.
  assert.equal(frontmatter({ title: "T", summary: "", credits: [] }, "u").includes("summary"), false);
  // Korean and quotes survive the round trip through JSON quoting.
  assert.match(frontmatter({ title: '기아 "EV9"' }, "u"), /title: "기아 \\"EV9\\""/);

  console.log("md.mjs: all checks passed");
}

if (process.argv[1] === new URL(import.meta.url).pathname) demo();
